package dev.vantafyn.feature.home.mcu

import java.util.UUID

data class McuMovie(
    val id: String,
    val title: String,
    val releaseYear: Int,
    val releaseOrder: Int,
    val timelineOrder: Int,
    val timelineSetting: String,
    val phase: String,
    val tmdbId: Int?,
    val imdbId: String?,
    val fallbackPosterPath: String,
    val overview: String? = null,
) {
    val fallbackPosterUrl: String
        get() = if (fallbackPosterPath.isNotBlank()) "https://image.tmdb.org/t/p/w500$fallbackPosterPath" else ""
}

enum class McuSortMode(val label: String) {
    Timeline("Timeline Order"),
    Release("Release Order"),
}

enum class McuFilterMode(val label: String) {
    All("All"),
    Watched("Watched"),
    Unwatched("Unwatched"),
    Missing("Not on server"),
}

data class McuWatchItemUi(
    val movie: McuMovie,
    val isOnServer: Boolean = false,
    val isPlayed: Boolean = false,
    val mediaItemId: UUID? = null,
    val serverImageUrl: String? = null,
    val serverBackdropUrl: String? = null,
    val playbackPositionPercentage: Float? = null,
) {
    val displayPosterUrl: String
        get() = serverImageUrl?.takeIf { it.isNotBlank() } ?: movie.fallbackPosterUrl
}

object McuMoviesCatalog {

    fun normalizeTitle(title: String): String {
        val clean = title.lowercase()
            .replace("marvel's ", "")
            .replace("marvel ", "")
            .replace(Regex("[^a-z0-9]"), "")
        return if (clean.startsWith("thefantasticfour")) clean.removePrefix("the") else clean
    }

    val movies: List<McuMovie> = listOf(
        McuMovie(
            id = "captain_america_1",
            title = "Captain America: The First Avenger",
            releaseYear = 2011,
            releaseOrder = 15,
            timelineOrder = 1,
            timelineSetting = "1942–1945 (World War II)",
            phase = "Phase 1",
            tmdbId = 1771,
            imdbId = "tt0458339",
            fallbackPosterPath = "/ytp1nd1utEr9nAi2jEBCiLClwqC.jpg",
            overview = "Steve Rogers is transformed into the world's first super-soldier and battles Hydra.",
        ),
        McuMovie(
            id = "x_men_first_class_2011",
            title = "X-Men: First Class",
            releaseYear = 2011,
            releaseOrder = 14,
            timelineOrder = 2,
            timelineSetting = "1962 (Cuban Missile Crisis)",
            phase = "X-Men Universe",
            tmdbId = 49538,
            imdbId = "tt1270798",
            fallbackPosterPath = "/hNEokmUke0dazoBhttFN0o3L7Xv.jpg",
            overview = "In the 1960s, Charles Xavier and Erik Lehnsherr unite mutants to prevent a nuclear war.",
        ),
        McuMovie(
            id = "x_men_days_of_future_past_2014",
            title = "X-Men: Days of Future Past",
            releaseYear = 2014,
            releaseOrder = 23,
            timelineOrder = 3,
            timelineSetting = "1973 (Paris Peace Accords)",
            phase = "X-Men Universe",
            tmdbId = 127585,
            imdbId = "tt1877832",
            fallbackPosterPath = "/tYfijzolzgoMOtegh1Y7j2Enorg.jpg",
            overview = "Wolverine travels back in time to 1973 to prevent a catastrophic mutant-hunting sentinel future.",
        ),
        McuMovie(
            id = "x_men_origins_wolverine_2009",
            title = "X-Men Origins: Wolverine",
            releaseYear = 2009,
            releaseOrder = 11,
            timelineOrder = 4,
            timelineSetting = "1979 (Three Mile Island)",
            phase = "X-Men Universe",
            tmdbId = 2080,
            imdbId = "tt0458525",
            fallbackPosterPath = "/yj8LbTju1p7CUJg7US2unSBk33s.jpg",
            overview = "The origin of Logan, his mutant brotherhood with Victor Creed, and the Weapon X program.",
        ),
        McuMovie(
            id = "x_men_apocalypse_2016",
            title = "X-Men: Apocalypse",
            releaseYear = 2016,
            releaseOrder = 30,
            timelineOrder = 5,
            timelineSetting = "1983 (The First Mutant)",
            phase = "X-Men Universe",
            tmdbId = 246655,
            imdbId = "tt3385516",
            fallbackPosterPath = "/ikA8UhYdTGpqbatFa93nIf6noSr.jpg",
            overview = "The world's first mutant, En Sabah Nur, awakens in 1983 to cleanse mankind.",
        ),
        McuMovie(
            id = "dark_phoenix_2019",
            title = "Dark Phoenix",
            releaseYear = 2019,
            releaseOrder = 43,
            timelineOrder = 6,
            timelineSetting = "1992 (The Cosmic Entity)",
            phase = "X-Men Universe",
            tmdbId = 320288,
            imdbId = "tt6565702",
            fallbackPosterPath = "/cCTJPelKGLhALq3r51A9uMonxKj.jpg",
            overview = "Jean Grey is struck by a mysterious cosmic force that unleashes uncontrollable power.",
        ),
        McuMovie(
            id = "captain_marvel",
            title = "Captain Marvel",
            releaseYear = 2019,
            releaseOrder = 41,
            timelineOrder = 7,
            timelineSetting = "1995 (Kree-Skrull War)",
            phase = "Phase 3",
            tmdbId = 299537,
            imdbId = "tt4154664",
            fallbackPosterPath = "/AtsgWhDnHTq68L0lLsUrCnM7TDC.jpg",
            overview = "Carol Danvers becomes one of the universe's most powerful heroes during a galactic war.",
        ),
        McuMovie(
            id = "x_men_2000",
            title = "X-Men",
            releaseYear = 2000,
            releaseOrder = 1,
            timelineOrder = 8,
            timelineSetting = "2000 (Statue of Liberty)",
            phase = "X-Men Universe",
            tmdbId = 36657,
            imdbId = "tt0120903",
            fallbackPosterPath = "/bRDAc4GogyS9ci3ow7UnInOcriN.jpg",
            overview = "Wolverine and Rogue find sanctuary at Xavier's School as Magneto plans a mutant uprising.",
        ),
        McuMovie(
            id = "spider_man_2002",
            title = "Spider-Man",
            releaseYear = 2002,
            releaseOrder = 2,
            timelineOrder = 9,
            timelineSetting = "2002 (With Great Power)",
            phase = "Spider-Man Legacy",
            tmdbId = 557,
            imdbId = "tt0145487",
            fallbackPosterPath = "/or6XJBVpcEbIkma0V9zshnbEtx4.jpg",
            overview = "Peter Parker is bitten by a genetically altered spider and faces the Green Goblin.",
        ),
        McuMovie(
            id = "x2_2003",
            title = "X2",
            releaseYear = 2003,
            releaseOrder = 3,
            timelineOrder = 10,
            timelineSetting = "2003 (Alkali Lake)",
            phase = "X-Men Universe",
            tmdbId = 36658,
            imdbId = "tt0290334",
            fallbackPosterPath = "/bst4alFUXCxISwdRUKSMhhkrX1M.jpg",
            overview = "The X-Men and Brotherhood unite when military scientist William Stryker attacks the school.",
        ),
        McuMovie(
            id = "spider_man_2_2004",
            title = "Spider-Man 2",
            releaseYear = 2004,
            releaseOrder = 4,
            timelineOrder = 11,
            timelineSetting = "2004 (Doctor Octopus)",
            phase = "Spider-Man Legacy",
            tmdbId = 558,
            imdbId = "tt0316654",
            fallbackPosterPath = "/aGuvNAaaZuWXYQQ6N2v7DeuP6mB.jpg",
            overview = "Peter Parker struggles with dual lives while battling brilliant scientist Otto Octavius.",
        ),
        McuMovie(
            id = "fantastic_four_2005",
            title = "Fantastic Four",
            releaseYear = 2005,
            releaseOrder = 5,
            timelineOrder = 12,
            timelineSetting = "2005 (Cosmic Rays)",
            phase = "Fantastic Four",
            tmdbId = 9738,
            imdbId = "tt0120667",
            fallbackPosterPath = "/4YMcYEFS8sFuW3soP1HVmgR3cSm.jpg",
            overview = "Four astronauts gain superpowers from cosmic radiation and clash with Victor Von Doom.",
        ),
        McuMovie(
            id = "x_men_the_last_stand_2006",
            title = "X-Men: The Last Stand",
            releaseYear = 2006,
            releaseOrder = 6,
            timelineOrder = 13,
            timelineSetting = "2006 (The Mutant Cure)",
            phase = "X-Men Universe",
            tmdbId = 36668,
            imdbId = "tt0376994",
            fallbackPosterPath = "/a2xicU8DpKtRizOHjQLC1JyCSRS.jpg",
            overview = "A mutant cure threatens peace as the resurrection of Jean Grey turns tragic on Alcatraz.",
        ),
        McuMovie(
            id = "spider_man_3_2007",
            title = "Spider-Man 3",
            releaseYear = 2007,
            releaseOrder = 7,
            timelineOrder = 14,
            timelineSetting = "2007 (The Symbiote)",
            phase = "Spider-Man Legacy",
            tmdbId = 559,
            imdbId = "tt0413300",
            fallbackPosterPath = "/qFmwhVUoUSXjkKRmca5yGDEXBIj.jpg",
            overview = "Peter Parker bonds with an alien symbiote while facing Sandman, New Goblin, and Venom.",
        ),
        McuMovie(
            id = "fantastic_four_2_2007",
            title = "Fantastic Four: Rise of the Silver Surfer",
            releaseYear = 2007,
            releaseOrder = 8,
            timelineOrder = 15,
            timelineSetting = "2007 (Galactus Approaches)",
            phase = "Fantastic Four",
            tmdbId = 1979,
            imdbId = "tt0486576",
            fallbackPosterPath = "/pyk3c1a4U6nxRJPljPQbP8elTSU.jpg",
            overview = "The Fantastic Four learn that the Silver Surfer has arrived to prepare Earth for destruction.",
        ),
        McuMovie(
            id = "iron_man_1",
            title = "Iron Man",
            releaseYear = 2008,
            releaseOrder = 9,
            timelineOrder = 16,
            timelineSetting = "2010 (Birth of the MCU)",
            phase = "Phase 1",
            tmdbId = 1726,
            imdbId = "tt0371746",
            fallbackPosterPath = "/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
            overview = "Billionaire industrialist Tony Stark builds an armored suit after being held captive in a cave.",
        ),
        McuMovie(
            id = "iron_man_2",
            title = "Iron Man 2",
            releaseYear = 2010,
            releaseOrder = 12,
            timelineOrder = 17,
            timelineSetting = "2011 (Fury's Big Week)",
            phase = "Phase 1",
            tmdbId = 10138,
            imdbId = "tt1228705",
            fallbackPosterPath = "/6WBeq40vW0X2kVO6jL2epG6zK7q.jpg",
            overview = "Tony Stark faces pressure from the government and a vengeful rival while battling palladium poisoning.",
        ),
        McuMovie(
            id = "incredible_hulk",
            title = "The Incredible Hulk",
            releaseYear = 2008,
            releaseOrder = 10,
            timelineOrder = 18,
            timelineSetting = "2011 (Fury's Big Week)",
            phase = "Phase 1",
            tmdbId = 1724,
            imdbId = "tt0800080",
            fallbackPosterPath = "/7slgLGE4v6Vf1zW2x9uBq1n9lGg.jpg",
            overview = "Bruce Banner seeks a cure for his monstrous alter ego while hunted by General Ross and the Abomination.",
        ),
        McuMovie(
            id = "thor_1",
            title = "Thor",
            releaseYear = 2011,
            releaseOrder = 13,
            timelineOrder = 19,
            timelineSetting = "2011 (Fury's Big Week)",
            phase = "Phase 1",
            tmdbId = 10195,
            imdbId = "tt0800369",
            fallbackPosterPath = "/prSfAi1xGrhLQNxVSUFh61xQ4Qx.jpg",
            overview = "The arrogant god Thor is cast out of Asgard to live on Earth, where he learns what it means to be a hero.",
        ),
        McuMovie(
            id = "avengers_1",
            title = "The Avengers",
            releaseYear = 2012,
            releaseOrder = 16,
            timelineOrder = 20,
            timelineSetting = "2012 (Battle of New York)",
            phase = "Phase 1",
            tmdbId = 24428,
            imdbId = "tt0848228",
            fallbackPosterPath = "/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
            overview = "Earth's Mightiest Heroes assemble to stop Loki and an alien invasion of New York City.",
        ),
        McuMovie(
            id = "amazing_spider_man_2012",
            title = "The Amazing Spider-Man",
            releaseYear = 2012,
            releaseOrder = 17,
            timelineOrder = 21,
            timelineSetting = "2012 (Oscorp & The Lizard)",
            phase = "Spider-Man Legacy",
            tmdbId = 1930,
            imdbId = "tt0422272",
            fallbackPosterPath = "/jexoNYnPd6vVrmygwF6QZmWPFdu.jpg",
            overview = "Peter Parker investigates his parents' disappearance, leading to Oscorp and Dr. Curt Connors.",
        ),
        McuMovie(
            id = "iron_man_3",
            title = "Iron Man 3",
            releaseYear = 2013,
            releaseOrder = 18,
            timelineOrder = 22,
            timelineSetting = "December 2012 (Clean Slate)",
            phase = "Phase 2",
            tmdbId = 68721,
            imdbId = "tt1300854",
            fallbackPosterPath = "/7sfbEnaARXDD5UCEsoZ0wVIiqEV.jpg",
            overview = "Tony Stark faces PTSD and the mysterious Mandarin following the Battle of New York.",
        ),
        McuMovie(
            id = "the_wolverine_2013",
            title = "The Wolverine",
            releaseYear = 2013,
            releaseOrder = 19,
            timelineOrder = 23,
            timelineSetting = "2013 (Japan / Immortality)",
            phase = "X-Men Universe",
            tmdbId = 76170,
            imdbId = "tt1430132",
            fallbackPosterPath = "/t2wVAcoRlKvEIVSbiYDb8d0QqqS.jpg",
            overview = "Vulnerable and stripped of his healing factor, Wolverine journeys into modern-day Japan.",
        ),
        McuMovie(
            id = "thor_dark_world",
            title = "Thor: The Dark World",
            releaseYear = 2013,
            releaseOrder = 20,
            timelineOrder = 24,
            timelineSetting = "2013 (The Convergence)",
            phase = "Phase 2",
            tmdbId = 76338,
            imdbId = "tt1981109",
            fallbackPosterPath = "/wp6OxE4poJ4G7c0U2ZIXasTSMR7.jpg",
            overview = "Thor reunites with Jane Foster as the dark elf Malekith seeks to plunge the universe into darkness.",
        ),
        McuMovie(
            id = "captain_america_winter_soldier",
            title = "Captain America: The Winter Soldier",
            releaseYear = 2014,
            releaseOrder = 21,
            timelineOrder = 25,
            timelineSetting = "2014 (Fall of S.H.I.E.L.D.)",
            phase = "Phase 2",
            tmdbId = 100402,
            imdbId = "tt1843866",
            fallbackPosterPath = "/tVFRpFw3xTed5nGQqW0SdKHMW40.jpg",
            overview = "Captain America and Black Widow uncover a conspiracy within S.H.I.E.L.D. and face the Winter Soldier.",
        ),
        McuMovie(
            id = "guardians_galaxy_1",
            title = "Guardians of the Galaxy",
            releaseYear = 2014,
            releaseOrder = 24,
            timelineOrder = 26,
            timelineSetting = "2014 (Power Stone)",
            phase = "Phase 2",
            tmdbId = 118340,
            imdbId = "tt2015381",
            fallbackPosterPath = "/r7vmZjiyZw9rpJMQJdXxyMu9bh.jpg",
            overview = "A group of intergalactic criminals band together to stop Ronan the Accuser from using an Infinity Stone.",
        ),
        McuMovie(
            id = "guardians_galaxy_2",
            title = "Guardians of the Galaxy Vol. 2",
            releaseYear = 2017,
            releaseOrder = 33,
            timelineOrder = 27,
            timelineSetting = "2014 (Ego the Living Planet)",
            phase = "Phase 3",
            tmdbId = 283995,
            imdbId = "tt3896198",
            fallbackPosterPath = "/y4MBh0EjBlMuOzv9axM4qJmLRbF.jpg",
            overview = "The Guardians struggle to keep their newfound family together as Peter Quill discovers his true parentage.",
        ),
        McuMovie(
            id = "amazing_spider_man_2_2014",
            title = "The Amazing Spider-Man 2",
            releaseYear = 2014,
            releaseOrder = 22,
            timelineOrder = 28,
            timelineSetting = "2014 (Electro & Green Goblin)",
            phase = "Spider-Man Legacy",
            tmdbId = 102382,
            imdbId = "tt1872181",
            fallbackPosterPath = "/bU7nTmvmy0h3VUP01v1T2imgH6N.jpg",
            overview = "Peter Parker battles Electro and Green Goblin while trying to protect Gwen Stacy.",
        ),
        McuMovie(
            id = "fantastic_four_2015",
            title = "Fantastic Four",
            releaseYear = 2015,
            releaseOrder = 27,
            timelineOrder = 29,
            timelineSetting = "2015 (Planet Zero)",
            phase = "Fantastic Four",
            tmdbId = 166424,
            imdbId = "tt1502712",
            fallbackPosterPath = "/cDroz5qSlP8xZ6tOpeYoPkBvKyL.jpg",
            overview = "Young scientists teleport to an alternate universe, altering their physical forms in shocking ways.",
        ),
        McuMovie(
            id = "avengers_age_of_ultron",
            title = "Avengers: Age of Ultron",
            releaseYear = 2015,
            releaseOrder = 25,
            timelineOrder = 30,
            timelineSetting = "2015 (Battle of Sokovia)",
            phase = "Phase 2",
            tmdbId = 99861,
            imdbId = "tt2395427",
            fallbackPosterPath = "/4ssDuvEDkS9NvmR19FuqaHvKcRS.jpg",
            overview = "Tony Stark's peacekeeping AI program goes rogue, forcing the Avengers to stop him from destroying humanity.",
        ),
        McuMovie(
            id = "ant_man_1",
            title = "Ant-Man",
            releaseYear = 2015,
            releaseOrder = 26,
            timelineOrder = 31,
            timelineSetting = "2015 (Pym Particles)",
            phase = "Phase 2",
            tmdbId = 102899,
            imdbId = "tt0478970",
            fallbackPosterPath = "/8c4a8kE7PizaGQQvvao9VIPno1e.jpg",
            overview = "Master thief Scott Lang dons the Ant-Man suit to stop Yellowjacket with Hank Pym.",
        ),
        McuMovie(
            id = "captain_america_civil_war",
            title = "Captain America: Civil War",
            releaseYear = 2016,
            releaseOrder = 29,
            timelineOrder = 32,
            timelineSetting = "2016 (The Sokovia Accords)",
            phase = "Phase 3",
            tmdbId = 271110,
            imdbId = "tt3498820",
            fallbackPosterPath = "/rAGiXaUfPzY7CDEyNKUofk3Kw2e.jpg",
            overview = "Political pressure to control the Avengers creates a rift between Captain America and Iron Man.",
        ),
        McuMovie(
            id = "black_widow",
            title = "Black Widow",
            releaseYear = 2021,
            releaseOrder = 46,
            timelineOrder = 33,
            timelineSetting = "2016 (The Red Room)",
            phase = "Phase 4",
            tmdbId = 497698,
            imdbId = "tt3480822",
            fallbackPosterPath = "/qAZ0wfzwfliofkv07mHYNzXOb46.jpg",
            overview = "Natasha Romanoff confronts the darker parts of her past when a dangerous conspiracy arises.",
        ),
        McuMovie(
            id = "black_panther_1",
            title = "Black Panther",
            releaseYear = 2018,
            releaseOrder = 36,
            timelineOrder = 34,
            timelineSetting = "2016 (King of Wakanda)",
            phase = "Phase 3",
            tmdbId = 284054,
            imdbId = "tt1825683",
            fallbackPosterPath = "/uxzzxijgPIY7slzFvMotPv8vlum.jpg",
            overview = "T'Challa returns home to the technologically advanced African nation of Wakanda to take his rightful place as king.",
        ),
        McuMovie(
            id = "spider_man_homecoming",
            title = "Spider-Man: Homecoming",
            releaseYear = 2017,
            releaseOrder = 34,
            timelineOrder = 35,
            timelineSetting = "Fall 2016 (The Vulture)",
            phase = "Phase 3",
            tmdbId = 315635,
            imdbId = "tt2250912",
            fallbackPosterPath = "/c24sv2weTHPsmDa7jEMN0m2P3RT.jpg",
            overview = "Peter Parker navigates high school life while fighting the Vulture under the mentorship of Tony Stark.",
        ),
        McuMovie(
            id = "deadpool_2016",
            title = "Deadpool",
            releaseYear = 2016,
            releaseOrder = 28,
            timelineOrder = 36,
            timelineSetting = "2016 (Maximum Effort)",
            phase = "X-Men Universe",
            tmdbId = 293660,
            imdbId = "tt1431045",
            fallbackPosterPath = "/3E53WEZJqP6aM84D8CckXx4pIHw.jpg",
            overview = "Wisecracking mercenary Wade Wilson undergoes rogue experiment that leaves him with accelerated healing.",
        ),
        McuMovie(
            id = "doctor_strange_1",
            title = "Doctor Strange",
            releaseYear = 2016,
            releaseOrder = 31,
            timelineOrder = 37,
            timelineSetting = "2016–2017 (Master of the Mystic Arts)",
            phase = "Phase 3",
            tmdbId = 284052,
            imdbId = "tt1211837",
            fallbackPosterPath = "/uGBVj3bEbCoIQDjjq91btupcy0x.jpg",
            overview = "A former neurosurgeon embarks on a journey of healing only to be drawn into the world of the mystic arts.",
        ),
        McuMovie(
            id = "thor_ragnarok",
            title = "Thor: Ragnarok",
            releaseYear = 2017,
            releaseOrder = 35,
            timelineOrder = 38,
            timelineSetting = "2017 (Destruction of Asgard)",
            phase = "Phase 3",
            tmdbId = 284053,
            imdbId = "tt3501632",
            fallbackPosterPath = "/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
            overview = "Imprisoned on the planet Sakaar, Thor must race against time to return to Asgard and stop Hela.",
        ),
        McuMovie(
            id = "ant_man_and_the_wasp",
            title = "Ant-Man and the Wasp",
            releaseYear = 2018,
            releaseOrder = 39,
            timelineOrder = 39,
            timelineSetting = "2018 (The Quantum Realm)",
            phase = "Phase 3",
            tmdbId = 363088,
            imdbId = "tt5095030",
            fallbackPosterPath = "/eivQmS3wqz9z1nQrr4uvxuYlaFl.jpg",
            overview = "Scott Lang teams up with Hope van Dyne to uncover secrets from their past in the Quantum Realm.",
        ),
        McuMovie(
            id = "deadpool_2_2018",
            title = "Deadpool 2",
            releaseYear = 2018,
            releaseOrder = 38,
            timelineOrder = 40,
            timelineSetting = "2018 (X-Force & Cable)",
            phase = "X-Men Universe",
            tmdbId = 383498,
            imdbId = "tt5463162",
            fallbackPosterPath = "/to0spRl1CMDvyUbOnbb4fTk3VAd.jpg",
            overview = "Deadpool forms a team of mutants called X-Force to protect a young mutant from time-traveling soldier Cable.",
        ),
        McuMovie(
            id = "venom_2018",
            title = "Venom",
            releaseYear = 2018,
            releaseOrder = 40,
            timelineOrder = 41,
            timelineSetting = "2018 (We Are Venom)",
            phase = "Sony Universe",
            tmdbId = 399579,
            imdbId = "tt1270797",
            fallbackPosterPath = "/xRWht48C2V8XNfzvPehyClOvDni.jpg",
            overview = "Journalist Eddie Brock gains superpowers after becoming the host of an alien symbiote.",
        ),
        McuMovie(
            id = "avengers_infinity_war",
            title = "Avengers: Infinity War",
            releaseYear = 2018,
            releaseOrder = 37,
            timelineOrder = 42,
            timelineSetting = "Spring 2018 (The Snap)",
            phase = "Phase 3",
            tmdbId = 299536,
            imdbId = "tt4154756",
            fallbackPosterPath = "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
            overview = "The Avengers and Guardians unite to prevent Thanos from collecting all six Infinity Stones.",
        ),
        McuMovie(
            id = "avengers_endgame",
            title = "Avengers: Endgame",
            releaseYear = 2019,
            releaseOrder = 42,
            timelineOrder = 43,
            timelineSetting = "2018 / 2023 (The Time Heist)",
            phase = "Phase 3",
            tmdbId = 299534,
            imdbId = "tt4154796",
            fallbackPosterPath = "/or06FN3Dka5tukK1e9sl16pB3iy.jpg",
            overview = "After Thanos wipes out half of all life, the remaining Avengers attempt a daring time heist to undo the devastation.",
        ),
        McuMovie(
            id = "the_new_mutants_2020",
            title = "The New Mutants",
            releaseYear = 2020,
            releaseOrder = 45,
            timelineOrder = 44,
            timelineSetting = "2020 (Milbury Hospital)",
            phase = "X-Men Universe",
            tmdbId = 340102,
            imdbId = "tt4682266",
            fallbackPosterPath = "/xiDGcXJTvu1lazFRYip6g1eLt9c.jpg",
            overview = "Five young mutants held in a secret facility fight to escape their pasts and save themselves.",
        ),
        McuMovie(
            id = "shang_chi",
            title = "Shang-Chi and the Legend of the Ten Rings",
            releaseYear = 2021,
            releaseOrder = 47,
            timelineOrder = 45,
            timelineSetting = "Spring 2024 (Ta Lo)",
            phase = "Phase 4",
            tmdbId = 566525,
            imdbId = "tt9376612",
            fallbackPosterPath = "/1BIoJGKbXjd2JWv8kgIIAcUmAcv.jpg",
            overview = "Shang-Chi must confront the past he thought he left behind when drawn into the Ten Rings organization.",
        ),
        McuMovie(
            id = "spider_man_far_from_home",
            title = "Spider-Man: Far From Home",
            releaseYear = 2019,
            releaseOrder = 44,
            timelineOrder = 46,
            timelineSetting = "Summer 2024 (Europe)",
            phase = "Phase 3",
            tmdbId = 429617,
            imdbId = "tt6320628",
            fallbackPosterPath = "/4q2hz2m8hubgvij98xWcnYOawny.jpg",
            overview = "Peter Parker travels to Europe on a school trip where he is recruited by Nick Fury to stop the Elementals.",
        ),
        McuMovie(
            id = "venom_2_2021",
            title = "Venom: Let There Be Carnage",
            releaseYear = 2021,
            releaseOrder = 48,
            timelineOrder = 47,
            timelineSetting = "Fall 2024 (Multiverse Crossing)",
            phase = "Sony Universe",
            tmdbId = 580489,
            imdbId = "tt7097896",
            fallbackPosterPath = "/pzKsRuKLFmYrW5Q0q8E8G78Tcgo.jpg",
            overview = "Eddie Brock and Venom face serial killer Cletus Kasady, before being pulled across the multiverse into Earth-616.",
        ),
        McuMovie(
            id = "eternals",
            title = "Eternals",
            releaseYear = 2021,
            releaseOrder = 49,
            timelineOrder = 48,
            timelineSetting = "Fall 2024 (The Emergence)",
            phase = "Phase 4",
            tmdbId = 524434,
            imdbId = "tt9032441",
            fallbackPosterPath = "/b6qUvvgJ5YCEvCwVPAubpgfdEFQ.jpg",
            overview = "Ancient immortal beings emerge from hiding after thousands of years to protect Earth from their Deviant counterparts.",
        ),
        McuMovie(
            id = "spider_man_no_way_home",
            title = "Spider-Man: No Way Home",
            releaseYear = 2021,
            releaseOrder = 50,
            timelineOrder = 49,
            timelineSetting = "Fall/Winter 2024 (Multiverse Incursion)",
            phase = "Phase 4",
            tmdbId = 634649,
            imdbId = "tt10872600",
            fallbackPosterPath = "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
            overview = "When a spell goes wrong, dangerous foes and heroes from across the multiverse enter Peter Parker's world.",
        ),
        McuMovie(
            id = "doctor_strange_multiverse_madness",
            title = "Doctor Strange in the Multiverse of Madness",
            releaseYear = 2022,
            releaseOrder = 51,
            timelineOrder = 50,
            timelineSetting = "Late 2024 (Illuminati of Earth-838)",
            phase = "Phase 4",
            tmdbId = 453395,
            imdbId = "tt9419884",
            fallbackPosterPath = "/9Gtg2DzBhmYamXBS1hKAhiwbBKS.jpg",
            overview = "Doctor Strange journeys into the multiverse with America Chavez to face the corrupted Scarlet Witch.",
        ),
        McuMovie(
            id = "black_panther_wakanda_forever",
            title = "Black Panther: Wakanda Forever",
            releaseYear = 2022,
            releaseOrder = 53,
            timelineOrder = 51,
            timelineSetting = "Spring 2025 (Talokan War)",
            phase = "Phase 4",
            tmdbId = 505642,
            imdbId = "tt9114286",
            fallbackPosterPath = "/sv1xJUazXeYqALzczSZ3O6nkH75.jpg",
            overview = "The leaders of Wakanda fight to protect their nation from intervening world powers in the wake of King T'Challa's death.",
        ),
        McuMovie(
            id = "thor_love_and_thunder",
            title = "Thor: Love and Thunder",
            releaseYear = 2022,
            releaseOrder = 52,
            timelineOrder = 52,
            timelineSetting = "Summer 2025 (Gorr the God Butcher)",
            phase = "Phase 4",
            tmdbId = 616037,
            imdbId = "tt10648342",
            fallbackPosterPath = "/pIkRyD18kl4F0b69duhtC9RVjh1.jpg",
            overview = "Thor enlists the help of Valkyrie, Korg, and ex-girlfriend Jane Foster to fight Gorr the God Butcher.",
        ),
        McuMovie(
            id = "ant_man_quantumania",
            title = "Ant-Man and the Wasp: Quantumania",
            releaseYear = 2023,
            releaseOrder = 54,
            timelineOrder = 53,
            timelineSetting = "2026 (Kang the Conqueror)",
            phase = "Phase 5",
            tmdbId = 640146,
            imdbId = "tt10954600",
            fallbackPosterPath = "/ngl2FKBlU4fhbdsrtdom9LVLBXw.jpg",
            overview = "Scott Lang and Hope van Dyne explore the Quantum Realm and face Kang the Conqueror.",
        ),
        McuMovie(
            id = "guardians_galaxy_3",
            title = "Guardians of the Galaxy Vol. 3",
            releaseYear = 2023,
            releaseOrder = 55,
            timelineOrder = 54,
            timelineSetting = "2026 (The High Evolutionary)",
            phase = "Phase 5",
            tmdbId = 447365,
            imdbId = "tt6791350",
            fallbackPosterPath = "/r2J02Z2OpNTctetGCSpkmneAZNV.jpg",
            overview = "The Guardians rally to defend the universe and protect Rocket Raccoon from his creator.",
        ),
        McuMovie(
            id = "the_marvels",
            title = "The Marvels",
            releaseYear = 2023,
            releaseOrder = 56,
            timelineOrder = 55,
            timelineSetting = "2026 (Incursion to Earth-10005)",
            phase = "Phase 5",
            tmdbId = 609681,
            imdbId = "tt10676048",
            fallbackPosterPath = "/9GBhzXMFjgcZ3FdR9w3bUMMTps5.jpg",
            overview = "Carol Danvers, Kamala Khan, and Monica Rambeau swap places when using powers, ending with an incursion to the X-Men universe.",
        ),
        McuMovie(
            id = "logan_2017",
            title = "Logan",
            releaseYear = 2017,
            releaseOrder = 32,
            timelineOrder = 56,
            timelineSetting = "2029 (Death of the Anchor Being)",
            phase = "X-Men Universe",
            tmdbId = 263115,
            imdbId = "tt3315342",
            fallbackPosterPath = "/fnbjcRDYn6YviCcePDnGdyAkYsB.jpg",
            overview = "In a dystopian 2029, an aging Wolverine and ailing Professor X care for Laura, a young mutant clone pursued by Reavers.",
        ),
        McuMovie(
            id = "deadpool_and_wolverine",
            title = "Deadpool & Wolverine",
            releaseYear = 2024,
            releaseOrder = 57,
            timelineOrder = 57,
            timelineSetting = "2024 / The Void (TVA Incursion)",
            phase = "Phase 5",
            tmdbId = 533535,
            imdbId = "tt6263850",
            fallbackPosterPath = "/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg",
            overview = "Deadpool is pulled from his peaceful life by the TVA and teams with a broken Wolverine variant to save his world.",
        ),
        McuMovie(
            id = "captain_america_brave_new_world",
            title = "Captain America: Brave New World",
            releaseYear = 2025,
            releaseOrder = 58,
            timelineOrder = 58,
            timelineSetting = "2026 (Red Hulk & Adamantium)",
            phase = "Phase 5",
            tmdbId = 823464,
            imdbId = "tt14513804",
            fallbackPosterPath = "/pzIddQEMWhWzfvLI3TwxUG2wYoo.jpg",
            overview = "Sam Wilson officially takes up the mantle of Captain America amid a global conspiracy and the Red Hulk.",
        ),
        McuMovie(
            id = "thunderbolts",
            title = "Thunderbolts*",
            releaseYear = 2025,
            releaseOrder = 59,
            timelineOrder = 59,
            timelineSetting = "2026 (The Sentry & Void)",
            phase = "Phase 5",
            tmdbId = 986056,
            imdbId = "tt20969586",
            fallbackPosterPath = "/m9EtP1YrzvhbgVpHdH2Vohb1Vvj.jpg",
            overview = "An irreverent team of reformed antiheroes and villains carry out covert operations for the government.",
        ),
        McuMovie(
            id = "fantastic_four_first_steps",
            title = "The Fantastic Four: First Steps",
            releaseYear = 2025,
            releaseOrder = 60,
            timelineOrder = 60,
            timelineSetting = "Retro-Future 1960s (Alternate Earth)",
            phase = "Phase 6",
            tmdbId = 617126,
            imdbId = "tt10676052",
            fallbackPosterPath = "/nf5qaSEvyYSNeFH0YhSs5EsBLX9.jpg",
            overview = "Marvel's First Family balances superhero life while defending Earth from the ravenous Galactus and Silver Surfer.",
        ),
        McuMovie(
            id = "spider_man_brand_new_day",
            title = "Spider-Man: Brand New Day",
            releaseYear = 2026,
            releaseOrder = 61,
            timelineOrder = 61,
            timelineSetting = "Post-No Way Home / Lead-up to Doomsday",
            phase = "Phase 6",
            tmdbId = 1084199,
            imdbId = "tt20245360",
            fallbackPosterPath = "/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
            overview = "Peter Parker begins anew on the streets of New York, leading directly into the incursions of the multiverse.",
        ),
        McuMovie(
            id = "avengers_doomsday",
            title = "Avengers: Doomsday",
            releaseYear = 2026,
            releaseOrder = 62,
            timelineOrder = 62,
            timelineSetting = "December 2026 (Battle Against Doctor Doom)",
            phase = "Phase 6",
            tmdbId = 1003596,
            imdbId = "tt21361450",
            fallbackPosterPath = "/7WsyChQLEftFiDOVTGkv3hFpyyt.jpg",
            overview = "The Avengers, the Fantastic Four, and heroes from across the multiverse clash with Doctor Victor von Doom.",
        ),
    )
}
