package dev.vantafyn.feature.home.pokemon

import java.util.UUID

data class PokemonMovie(
    val id: String,
    val title: String,
    val releaseYear: Int,
    val releaseOrder: Int,
    val timelineOrder: Int,
    val timelineSetting: String,
    val era: String,
    val tmdbId: Int?,
    val imdbId: String?,
    val fallbackPosterPath: String,
    val overview: String? = null,
) {
    val fallbackPosterUrl: String
        get() = if (fallbackPosterPath.isNotBlank()) "https://image.tmdb.org/t/p/w500$fallbackPosterPath" else ""
}

enum class PokemonSortMode(val label: String) {
    Release("Release Order"),
    Timeline("Timeline Order"),
}

enum class PokemonFilterMode(val label: String) {
    All("All"),
    Watched("Watched"),
    Unwatched("Unwatched"),
    Missing("Not on server"),
}

data class PokemonWatchItemUi(
    val movie: PokemonMovie,
    val isOnServer: Boolean = false,
    val isPlayed: Boolean = false,
    val mediaItemId: UUID? = null,
    val serverImageUrl: String? = null,
    val serverBackdropUrl: String? = null,
    val playbackPositionPercentage: Float? = null,
) {
    val displayPosterUrl: String
        get() = serverImageUrl?.takeIf { it.isNotBlank() } ?: movie.fallbackPosterUrl
}

object PokemonMoviesCatalog {

    fun normalizeTitle(title: String): String {
        return title.lowercase()
            .replace("é", "e")
            .replace(Regex("[^a-z0-9]"), "")
    }

    val movies: List<PokemonMovie> = listOf(
        PokemonMovie(
            id = "pokemon_the_first_movie_1998",
            title = "Pokémon: The First Movie - Mewtwo Strikes Back",
            releaseYear = 1998,
            releaseOrder = 1,
            timelineOrder = 1,
            timelineSetting = "Indigo Plateau Era",
            era = "Generation I",
            tmdbId = 10228,
            imdbId = "tt0190641",
            fallbackPosterPath = "/6YPzBcMH0aPNTvdXNCDLY0zdE1g.jpg",
            overview = "Scientists genetically create a new Pokémon, Mewtwo, but the results prove disastrous when Mewtwo turns rogue.",
        ),
        PokemonMovie(
            id = "pokemon_the_movie_2000_1999",
            title = "Pokémon the Movie 2000: The Power of One",
            releaseYear = 1999,
            releaseOrder = 2,
            timelineOrder = 2,
            timelineSetting = "Orange Islands Era",
            era = "Generation I",
            tmdbId = 12599,
            imdbId = "tt0210234",
            fallbackPosterPath = "/6u65C8aG4krAVyHsTjAMF7ucTDH.jpg",
            overview = "Ash Ketchum must rescue the three legendary birds when a villainous collector disrupts the natural order.",
        ),
        PokemonMovie(
            id = "pokemon_3_the_movie_2000",
            title = "Pokémon 3: The Movie - Spell of the Unown",
            releaseYear = 2000,
            releaseOrder = 3,
            timelineOrder = 3,
            timelineSetting = "Johto Journeys Era",
            era = "Generation II",
            tmdbId = 10991,
            imdbId = "tt0235679",
            fallbackPosterPath = "/hrBWiMWnD7mheMx846ycUWA3ohs.jpg",
            overview = "When the legendary Unown trap Greenfield in crystal and create Entei, Ash must rescue his mother.",
        ),
        PokemonMovie(
            id = "pokemon_4ever_2001",
            title = "Pokémon 4Ever: Celebi - Voice of the Forest",
            releaseYear = 2001,
            releaseOrder = 4,
            timelineOrder = 4,
            timelineSetting = "Johto League Champions Era",
            era = "Generation II",
            tmdbId = 12600,
            imdbId = "tt0287635",
            fallbackPosterPath = "/thz83PS9twtVBEEAM59J1bh75nU.jpg",
            overview = "Ash and friends encounter a boy who has time-traveled forty years into the future with Celebi.",
        ),
        PokemonMovie(
            id = "pokemon_heroes_2002",
            title = "Pokémon Heroes: Latios & Latias",
            releaseYear = 2002,
            releaseOrder = 5,
            timelineOrder = 5,
            timelineSetting = "Master Quest Era",
            era = "Generation II",
            tmdbId = 33875,
            imdbId = "tt0347791",
            fallbackPosterPath = "/eySv5rdYLW1k6LxepxCNl8ND26R.jpg",
            overview = "In the water city of Alto Mare, Ash protects legendary guardians Latios and Latias from thieves.",
        ),
        PokemonMovie(
            id = "pokemon_jirachi_wish_maker_2003",
            title = "Pokémon: Jirachi - Wish Maker",
            releaseYear = 2003,
            releaseOrder = 6,
            timelineOrder = 6,
            timelineSetting = "Advanced Era",
            era = "Generation III",
            tmdbId = 36218,
            imdbId = "tt0420076",
            fallbackPosterPath = "/jbH0tIEymhyd6uk4xV4vrS6qybV.jpg",
            overview = "The Millennium Comet brings the mythical Jirachi awake for seven days, attracting the attention of a former Team Magma scientist.",
        ),
        PokemonMovie(
            id = "pokemon_destiny_deoxys_2004",
            title = "Pokémon: Destiny Deoxys",
            releaseYear = 2004,
            releaseOrder = 7,
            timelineOrder = 7,
            timelineSetting = "Advanced Challenge Era",
            era = "Generation III",
            tmdbId = 34065,
            imdbId = "tt0435286",
            fallbackPosterPath = "/3UV4evNh70gvPZB9KJEoh3a9B6I.jpg",
            overview = "When extraterrestrial Pokémon Deoxys crashes to Earth, Rayquaza initiates an epic battle in the high-tech city of LaRousse.",
        ),
        PokemonMovie(
            id = "pokemon_lucario_and_the_mystery_of_mew_2005",
            title = "Pokémon: Lucario and the Mystery of Mew",
            releaseYear = 2005,
            releaseOrder = 8,
            timelineOrder = 8,
            timelineSetting = "Advanced Battle Era",
            era = "Generation III",
            tmdbId = 34067,
            imdbId = "tt0875609",
            fallbackPosterPath = "/3A3WiPXPmWVhXC7bGSiqtsYY9z6.jpg",
            overview = "Centuries after being sealed in a staff by Sir Aaron, Lucario awakens and joins Ash to save Pikachu from the Tree of Beginning.",
        ),
        PokemonMovie(
            id = "pokemon_ranger_and_the_temple_of_the_sea_2006",
            title = "Pokémon Ranger and the Temple of the Sea",
            releaseYear = 2006,
            releaseOrder = 9,
            timelineOrder = 9,
            timelineSetting = "Battle Frontier Era",
            era = "Generation III",
            tmdbId = 16808,
            imdbId = "tt1000095",
            fallbackPosterPath = "/jZOi06xHjsG1VqbiIwS8GkyrAOn.jpg",
            overview = "Ash and May team up with a Pokémon Ranger to return the legendary Prince of the Sea, Manaphy, to the underwater temple Samiya.",
        ),
        PokemonMovie(
            id = "pokemon_the_rise_of_darkrai_2007",
            title = "Pokémon: The Rise of Darkrai",
            releaseYear = 2007,
            releaseOrder = 10,
            timelineOrder = 10,
            timelineSetting = "Diamond and Pearl Era",
            era = "Generation IV",
            tmdbId = 25961,
            imdbId = "tt1226251",
            fallbackPosterPath = "/yElGG6lxLtQXcgBVzF7Xxq7YRa2.jpg",
            overview = "As space-time tears apart during Dialga and Palkia's cosmic battle over Alamos Town, Darkrai steps in as an unexpected protector.",
        ),
        PokemonMovie(
            id = "pokemon_giratina_and_the_sky_warrior_2008",
            title = "Pokémon: Giratina and the Sky Warrior",
            releaseYear = 2008,
            releaseOrder = 11,
            timelineOrder = 11,
            timelineSetting = "DP Battle Dimension Era",
            era = "Generation IV",
            tmdbId = 47292,
            imdbId = "tt1160525",
            fallbackPosterPath = "/e3T08IL68EVcrUPiJLVN9KSGlXs.jpg",
            overview = "Shaymin leads Ash into the Reverse World where Giratina seeks revenge on Dialga for polluting its home dimension.",
        ),
        PokemonMovie(
            id = "pokemon_arceus_and_the_jewel_of_life_2009",
            title = "Pokémon: Arceus and the Jewel of Life",
            releaseYear = 2009,
            releaseOrder = 12,
            timelineOrder = 12,
            timelineSetting = "DP Galactic Battles Era",
            era = "Generation IV",
            tmdbId = 39057,
            imdbId = "tt1468843",
            fallbackPosterPath = "/tpqguVMKyPbINe0GYmMwduoaUar.jpg",
            overview = "Ash journeys into the ancient past to right a historic betrayal before the Creator Pokémon Arceus passes judgment upon mankind.",
        ),
        PokemonMovie(
            id = "pokemon_zoroark_master_of_illusions_2010",
            title = "Pokémon: Zoroark - Master of Illusions",
            releaseYear = 2010,
            releaseOrder = 13,
            timelineOrder = 13,
            timelineSetting = "DP Sinnoh League Victors Era",
            era = "Generation IV",
            tmdbId = 50087,
            imdbId = "tt1690470",
            fallbackPosterPath = "/tWgH64RZmm2rIHtO2DNnfN3DZa8.jpg",
            overview = "In Crown City, an unscrupulous businessman manipulates Zoroark into transforming into Raikou, Entei, and Suicune.",
        ),
        PokemonMovie(
            id = "pokemon_black_victini_and_reshiram_2011",
            title = "Pokémon the Movie: Black - Victini and Reshiram",
            releaseYear = 2011,
            releaseOrder = 14,
            timelineOrder = 14,
            timelineSetting = "Black & White Era",
            era = "Generation V",
            tmdbId = 115223,
            imdbId = "tt1961324",
            fallbackPosterPath = "/SuIAXmxlbImWHobCkCWCHAeg03.jpg",
            overview = "In Eindoak Town, Ash befriends the Victory Pokémon Victini and must awaken Reshiram to restore the Dragon Force.",
        ),
        PokemonMovie(
            id = "pokemon_kyurem_vs_the_sword_of_justice_2012",
            title = "Pokémon the Movie: Kyurem vs. the Sword of Justice",
            releaseYear = 2012,
            releaseOrder = 15,
            timelineOrder = 15,
            timelineSetting = "BW Rival Destinies Era",
            era = "Generation V",
            tmdbId = 150213,
            imdbId = "tt2549540",
            fallbackPosterPath = "/7gQEAR8aaCQRtJi7wq26ST5hukn.jpg",
            overview = "Keldeo aspires to become one of the Swords of Justice by facing Kyurem, the boundary-breaking Dragon Pokémon.",
        ),
        PokemonMovie(
            id = "pokemon_genesect_and_the_legend_awakened_2013",
            title = "Pokémon the Movie: Genesect and the Legend Awakened",
            releaseYear = 2013,
            releaseOrder = 16,
            timelineOrder = 16,
            timelineSetting = "BW Adventures in Unova Era",
            era = "Generation V",
            tmdbId = 227679,
            imdbId = "tt3257582",
            fallbackPosterPath = "/l921PT8ZDeAD4YWDaB5Uke89r9b.jpg",
            overview = "Five prehistoric Genesect terrorize New Tork City, prompting a mega-evolving Mewtwo to battle them.",
        ),
        PokemonMovie(
            id = "pokemon_diancie_and_the_cocoon_of_destruction_2014",
            title = "Pokémon the Movie: Diancie and the Cocoon of Destruction",
            releaseYear = 2014,
            releaseOrder = 17,
            timelineOrder = 17,
            timelineSetting = "XY Era",
            era = "Generation VI",
            tmdbId = 303903,
            imdbId = "tt3918368",
            fallbackPosterPath = "/rA0KbJZbBt2fMmZs8bwPZnzFfDc.jpg",
            overview = "Princess Diancie seeks Xerneas to create the Heart Diamond, but accidentally awakens Yveltal, the cocoon of destruction.",
        ),
        PokemonMovie(
            id = "pokemon_hoopa_and_the_clash_of_ages_2015",
            title = "Pokémon the Movie: Hoopa and the Clash of Ages",
            releaseYear = 2015,
            releaseOrder = 18,
            timelineOrder = 18,
            timelineSetting = "XY Kalos Quest Era",
            era = "Generation VI",
            tmdbId = 350499,
            imdbId = "tt4503906",
            fallbackPosterPath = "/6kXRevMC1XSywmxqqRHuBcZlROT.jpg",
            overview = "The mischievous mythical Hoopa summons legendary Pokémon across generations into Dahara City in a clash of titans.",
        ),
        PokemonMovie(
            id = "pokemon_volcanion_and_the_mechanical_marvel_2016",
            title = "Pokémon the Movie: Volcanion and the Mechanical Marvel",
            releaseYear = 2016,
            releaseOrder = 19,
            timelineOrder = 19,
            timelineSetting = "XYZ Era",
            era = "Generation VI",
            tmdbId = 382190,
            imdbId = "tt5889204",
            fallbackPosterPath = "/4hdbuM6qBrHH0hX4sD8pNsXmalm.jpg",
            overview = "Ash becomes magnetically bound to the mythical Volcanion on a rescue mission to save Magearna in the Azoth Kingdom.",
        ),
        PokemonMovie(
            id = "pokemon_i_choose_you_2017",
            title = "Pokémon the Movie: I Choose You!",
            releaseYear = 2017,
            releaseOrder = 20,
            timelineOrder = 20,
            timelineSetting = "Alternate Continuity - Beginning",
            era = "Generation VII",
            tmdbId = 436931,
            imdbId = "tt6595896",
            fallbackPosterPath = "/7vWiCtO1pa0oSG6QTyVKd8eyLLk.jpg",
            overview = "A celebration of 20 years of Pokémon, retelling Ash and Pikachu's first encounter and their quest to find the legendary Ho-Oh.",
        ),
        PokemonMovie(
            id = "pokemon_the_power_of_us_2018",
            title = "Pokémon the Movie: The Power of Us",
            releaseYear = 2018,
            releaseOrder = 21,
            timelineOrder = 21,
            timelineSetting = "Alternate Continuity - Fula City",
            era = "Generation VII",
            tmdbId = 494407,
            imdbId = "tt8108230",
            fallbackPosterPath = "/5oXKbOQOsPaLscHCqHjvi7hegOJ.jpg",
            overview = "Ash and Pikachu visit Fula City's annual Wind Festival and unite with diverse townspeople to save the city and summon Lugia.",
        ),
        PokemonMovie(
            id = "pokemon_mewtwo_strikes_back_evolution_2019",
            title = "Pokémon: Mewtwo Strikes Back - Evolution",
            releaseYear = 2019,
            releaseOrder = 22,
            timelineOrder = 22,
            timelineSetting = "3D CGI Re-imagining",
            era = "Generation VII",
            tmdbId = 571891,
            imdbId = "tt8856470",
            fallbackPosterPath = "/rtlyO2oIMcCx2DbOM52XO2rAcgn.jpg",
            overview = "Full CGI 3D re-imagining of the iconic original 1998 theatrical Pokémon film Mewtwo Strikes Back.",
        ),
        PokemonMovie(
            id = "pokemon_secrets_of_the_jungle_2020",
            title = "Pokémon the Movie: Secrets of the Jungle",
            releaseYear = 2020,
            releaseOrder = 23,
            timelineOrder = 23,
            timelineSetting = "Forest of Okoya",
            era = "Generation VIII",
            tmdbId = 662708,
            imdbId = "tt11819890",
            fallbackPosterPath = "/9Ow7PJcAHMMxgSIjCW6RnRqE9OA.jpg",
            overview = "Deep in the Forest of Okoya, Zarude raises a human boy named Koko who encounters Ash and Pikachu when danger threatens the Great Tree.",
        ),
        PokemonMovie(
            id = "pokemon_detective_pikachu_2019",
            title = "Pokémon Detective Pikachu",
            releaseYear = 2019,
            releaseOrder = 24,
            timelineOrder = 24,
            timelineSetting = "Ryme City (Live Action)",
            era = "Live Action",
            tmdbId = 447404,
            imdbId = "tt5884052",
            fallbackPosterPath = "/uhWvnFgg3BNlcUz0Re1HfQqIcCD.jpg",
            overview = "In a world where people collect Pokémon to do battle, a boy comes across an intelligent talking Pikachu who seeks to be a detective.",
        ),
    )
}
